### ISSUE TITLE
Create subinterface to hold the unique validation methods for different types of media

### ISSUE THREAD

**Issue by AgLyx3** [AgLyx3/Group-Sprint-1-Bookazon#38]
**Description:**
After expanding the system to incorporate different media subclasses and adding new fields to those classes, a general validation class also requires expansion to incorporate unique checkers for those unique fields.

**Code Snippet:**

For example, in the DVDs we have additional ```director``` and ```runtime``` to check.
```java
public DVDs(String title, String author, int yearPublished, double price, String director, int runtime) {
        super(title, author, yearPublished, price);
        this.director = director;
        this.runtime = runtime;
    }
```

**Solution:**
Create multiple subinterface that extend the current itemValidation interface.

**Comment by zaynabtariq** [comment]
Created subinterfaces for the different media types, it still needs to be integrated with rest of the code.
