### ISSUE TITLE
Fix Data Clumps of updateBookDetails method in Bookazon Class

### ISSUE THREAD

**Issue by zaynabtariq** [AgLyx3/Group-Sprint-1-Bookazon#4]
The ```updateBookDetails``` method in the ```Bookzon``` class violates Open-closed principle  and has code smell (data clumps).

**Comment by cathymonkey** [comment]
**Description:**

The ```updateBookDetails``` method in the ```Bookzon``` class has taken too many arguments and handles multiple updates of a book at once (Code smell: data clumps). This makes the code hard to read and maintain (violating "Open for extension" principle). For example, if we want to add a new attribute ```stockQuantity``` of the book, we will have to add an extra argument to the old existing method. 

Code snippet: 

Here's the current (problematic) implementation of the ```updateBookDetails``` method.

```.java
public void updateBookDetails(Book book, String newTitle, String newAuthor, int newYearPublished, double newPrice, boolean isPaperback) {
        book.setTitle(newTitle);
        book.setAuthor(newAuthor);
        book.setYearPublished(newYearPublished);
        book.setPrice(newPrice);
        book.setPaperback(isPaperback);
    }
```
**Suggested solution:**
Split the functionalities of the ```updateBookDetails``` method into several methods below to update a specific aspect of the book by calling setters in the ```book``` class.  The following are the new methods:

-  ```updateBookTitle```: update book title 
- ```updateBookPrice```: update book price 
-  ```updateBookAuthor```: update book author(s) 
-  ```updateBookYearPublished```: update book year published
-  ```updateBookIsPaperback```: update book year published

So, in the future,  we can update any aspect of the book by calling the corresponding method as each method updates a single attribute of the book independently.  If we want to add new attributes to a book, we can add a new corresponding method without modifying other methods.
