### ISSUE TITLE
Improve Encapsulation in User-Cart Interaction

### ISSUE THREAD

**Issue by zaynabtariq** [AgLyx3/Group-Sprint-1-Bookazon#8]
**Description:**

The ```addToCart``` and ```removeFromCart``methods in the User class indicate feature envy code smell, and the exact implementation of these methods should be moved to the cart class. Additionally, they are creating a new Cart() object in the argument, resulting in a violation of dependency inversion.

**Code Snippet:**

![image](https://github.com/user-attachments/assets/1310b1c7-75a0-4f73-bb3a-e8c0a8cba70f)

**Solution:**

Update the Cart class to provide methods for item manipulation
Update the User class to use these methods instead of directly accessing the Cart's item list.

**Comment by dfan26colbyedu** [comment]
Issue fixed.
